//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_SQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODPOWIEDZ
    {
        public int ID_ODPOWIEDZI { get; set; }
        public string ODPOWIEDZ1 { get; set; }
        public int ID_PYTANIE { get; set; }
        public int ID_TEST { get; set; }
        public int ID_UZYTKOWNIKA { get; set; }
    
        public virtual PYTANIE PYTANIE { get; set; }
        public virtual TEST TEST { get; set; }
        public virtual UZYTKOWNIK UZYTKOWNIK { get; set; }
    }
}
