//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_SQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PYTANIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PYTANIE()
        {
            this.ODPOWIEDZ = new HashSet<ODPOWIEDZ>();
        }
    
        public int ID_PYTANIE { get; set; }
        public string PYTANIE1 { get; set; }
        public int ID_TEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODPOWIEDZ> ODPOWIEDZ { get; set; }
        public virtual TEST TEST { get; set; }
    }
}
