//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja_SQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZYTKOWNIK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UZYTKOWNIK()
        {
            this.BAZA_DANYCH = new HashSet<BAZA_DANYCH>();
            this.ODPOWIEDZ = new HashSet<ODPOWIEDZ>();
            this.TEST = new HashSet<TEST>();
        }
    
        public int ID_UZYTKOWNIKA { get; set; }
        public string IMIE { get; set; }
        public string NAZWISKO { get; set; }
        public int NR_INDEKSU { get; set; }
        public string EMAIL { get; set; }
        public string TYP_KONTA { get; set; }
        public string LOGIN { get; set; }
        public string HASLO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAZA_DANYCH> BAZA_DANYCH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ODPOWIEDZ> ODPOWIEDZ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TEST> TEST { get; set; }
    }
}
